export type ExerciseId = "push-up" | "squat" | "plank" | "knee-push-up" | "forward-lunge" | "glute-bridge" | "side-plank" | "jumping-jack" | "high-knees";
export type Exercise = {
  id: ExerciseId; name: string; english: string; category: string; muscles: string; difficulty: string;
  image: string; target: number; unit: "ครั้ง" | "วินาที"; sets: number; rest: number;
  cue: string; steps: string[]; wide: boolean; cameraAngle: "ด้านข้าง" | "ด้านหน้า"; bilateral?: boolean;
};

export const exercises: Exercise[] = [
  { id: "push-up", name: "วิดพื้น", english: "Push-up", category: "ช่วงบน", muscles: "อก · ไหล่ · หลังแขน", difficulty: "เริ่มต้น", image: "/exercises/push-up.png", target: 10, unit: "ครั้ง", sets: 3, rest: 60, cue: "ลำตัวเป็นเส้นตรง ลงให้ลึก แล้วดันขึ้นจนแขนเกือบสุด", steps: ["วางมือกว้างกว่าไหล่เล็กน้อยและเหยียดลำตัวตรง", "งอศอกลดอกลงใกล้พื้น โดยไม่ปล่อยสะโพกตก", "ดันกลับขึ้นจนแขนเกือบเหยียดสุด แล้วเริ่มครั้งถัดไป"], wide: true, cameraAngle: "ด้านข้าง" },
  { id: "squat", name: "สควอต", english: "Bodyweight squat", category: "ช่วงล่าง", muscles: "ต้นขา · สะโพก", difficulty: "เริ่มต้น", image: "/exercises/squat.png", target: 12, unit: "ครั้ง", sets: 3, rest: 60, cue: "ย่อตัวโดยให้เท้าวางเต็มพื้น แล้วลุกกลับขึ้น", steps: ["ยืนแยกเท้าประมาณความกว้างไหล่", "ดันสะโพกไปด้านหลังและย่อเข่าลงตามช่วงที่สบาย", "กดเท้าลงพื้นและลุกกลับมายืนตรง"], wide: false, cameraAngle: "ด้านข้าง" },
  { id: "plank", name: "แพลงก์", english: "Forearm plank", category: "แกนกลาง", muscles: "หน้าท้อง · แกนกลาง", difficulty: "เริ่มต้น", image: "/exercises/plank.png", target: 30, unit: "วินาที", sets: 3, rest: 45, cue: "เกร็งหน้าท้อง รักษาแนวไหล่ถึงส้นเท้าให้ตรง", steps: ["วางข้อศอกใต้หัวไหล่และเหยียดขาไปด้านหลัง", "เกร็งหน้าท้องและสะโพก ไม่แอ่นหลัง", "หายใจตามปกติและรักษาท่าจนครบเวลา"], wide: true, cameraAngle: "ด้านข้าง" },
  { id: "knee-push-up", name: "วิดพื้นแบบคุกเข่า", english: "Bent-knee push-up", category: "ช่วงบน", muscles: "อก · ไหล่ · หลังแขน", difficulty: "เริ่มต้น", image: "/exercises/knee-push-up.png", target: 8, unit: "ครั้ง", sets: 2, rest: 60, cue: "คงแนวไหล่ถึงเข่าให้ตรง ลงและดันขึ้นให้ครบช่วง", steps: ["คุกเข่า วางมือกว้างระดับไหล่ เกร็งลำตัว", "งอศอกลดหน้าอกใกล้พื้น โดยสะโพกไม่ยกหรือหย่อน", "ดันกลับจนแขนเหยียด แล้วเริ่มครั้งใหม่"], wide: true, cameraAngle: "ด้านข้าง" },
  { id: "forward-lunge", name: "ลันจ์ก้าวหน้า", english: "Forward lunge", category: "ช่วงล่าง", muscles: "ต้นขา · สะโพก · การทรงตัว", difficulty: "ปานกลาง", image: "/exercises/forward-lunge.png", target: 8, unit: "ครั้ง", sets: 2, rest: 60, cue: "ก้าวไปข้างหน้า ย่อเข่าลง แล้วดันกลับมายืน", steps: ["ยืนตรง เลือกขาที่จะฝึกแล้วก้าวไปข้างหน้า", "ย่อเข่าทั้งสองข้างโดยรักษาลำตัวตั้งตรง", "ดันเท้าหน้ากลับมายืนตรง นับหนึ่งครั้ง ทำอีกข้างให้เท่ากัน"], wide: false, cameraAngle: "ด้านข้าง", bilateral: true },
  { id: "glute-bridge", name: "สะพานยกสะโพก", english: "Glute bridge", category: "ช่วงล่าง", muscles: "สะโพก · แกนกลาง", difficulty: "เริ่มต้น", image: "/exercises/glute-bridge.png", target: 12, unit: "ครั้ง", sets: 2, rest: 45, cue: "กดส้นเท้า ยกสะโพกจนไหล่ถึงเข่าเป็นแนว แล้วค่อยลดลง", steps: ["นอนหงาย งอเข่า วางเท้าราบกับพื้น", "เกร็งหน้าท้องและสะโพก ยกสะโพกโดยไม่แอ่นหลัง", "ลดสะโพกกลับลงอย่างควบคุม"], wide: true, cameraAngle: "ด้านข้าง" },
  { id: "side-plank", name: "แพลงก์ข้าง", english: "Side plank", category: "แกนกลาง", muscles: "หน้าท้องด้านข้าง · สะโพก", difficulty: "ปานกลาง", image: "/exercises/side-plank.png", target: 20, unit: "วินาที", sets: 2, rest: 45, cue: "วางศอกใต้ไหล่ ยกสะโพกจนลำตัวเป็นเส้นตรง", steps: ["นอนตะแคง วางศอกใต้ไหล่ เหยียดขาและวางเท้าซ้อนกัน", "เกร็งลำตัว ยกสะโพกให้แนวไหล่ สะโพก และข้อเท้าตรงกัน", "หายใจสม่ำเสมอ จับเวลาแต่ละข้างให้เท่ากัน"], wide: true, cameraAngle: "ด้านหน้า", bilateral: true },
  { id: "jumping-jack", name: "กระโดดตบ", english: "Jumping jack", category: "คาร์ดิโอ", muscles: "ทั้งตัว · หัวใจ", difficulty: "เริ่มต้น", image: "/exercises/jumping-jack.png", target: 20, unit: "ครั้ง", sets: 2, rest: 45, cue: "กางขาพร้อมยกแขนเหนือศีรษะ แล้วกลับมายืนชิด", steps: ["ยืนเท้าชิด แขนอยู่ข้างตัว", "กระโดดกางขาและยกแขนขึ้นเหนือศีรษะ", "กระโดดกลับเท้าชิดและลดแขนลง นับหนึ่งครั้ง"], wide: false, cameraAngle: "ด้านหน้า" },
  { id: "high-knees", name: "ยกเข่าสูงสลับข้าง", english: "High knees", category: "คาร์ดิโอ", muscles: "ต้นขา · สะโพก · หัวใจ", difficulty: "เริ่มต้น", image: "/exercises/high-knees.png", target: 20, unit: "ครั้ง", sets: 2, rest: 45, cue: "ยกเข่าทีละข้างถึงระดับสะโพกแล้ววางเท้ากลับ", steps: ["ยืนตรงและเว้นพื้นที่รอบตัว", "ยกเข่าข้างหนึ่งขึ้นใกล้ระดับสะโพกโดยไม่เอนตัวมาก", "วางเท้ากลับพื้น แล้วสลับอีกข้าง นับข้างละหนึ่งครั้ง"], wide: false, cameraAngle: "ด้านหน้า" },
];

export const byId = (id: ExerciseId) => exercises.find((exercise) => exercise.id === id)!;
